### ISSUE TITLE
PHP SDK error

### ISSUE THREAD

**Issue by geethansip** [opentok/OpenTok-PHP-SDK#223]
getting the below error when accessing the url http://localhost:8080. running the PHP application on windows 10.

Details
Type: GuzzleHttp\Exception\ClientException
Code: 403
Message: Client error: `POST https://api.opentok.com/session/create` resulted in a `403 Forbidden` response: <?xml version="1.0" encoding="UTF-8" standalone="yes"?><errorPayload><code>-1</code><message>issued time cannot be great (truncated...)
File: C:\OpenTok-PHP-SDK-master\OpenTok-PHP-SDK-master\sample\HelloWorld\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php
Line: 113
Trace
#0 C:\OpenTok-PHP-SDK-master\OpenTok-PHP-SDK-master\sample\HelloWorld\vendor\guzzlehttp\guzzle\src\Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 C:\OpenTok-PHP-SDK-master\OpenTok-PHP-SDK-master\sample\HelloWorld\vendor\guzzlehttp\promises\src\Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 C:\OpenTok-PHP-SDK-master\OpenTok-PHP-SDK-master\sample\HelloWorld\vendor\guzzlehttp\promises\src\Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 C:\OpenTok-PHP-SDK-master\OpenTok-PHP-SDK-master\sample\HelloWorld\vendor\guzzlehttp\promises\src\TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 C:\OpenTok-PHP-SDK-master\OpenTok-PHP-SDK-master\sample\HelloWorld\vendor\guzzlehttp\promises\src\Promise.php(246): GuzzleHttp\Promise\TaskQueue->run(true)
#5 C:\OpenTok-PHP-SDK-master\OpenTok-PHP-SDK-master\sample\HelloWorld\vendor\guzzlehttp\promises\src\Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn()
#6 C:\OpenTok-PHP-SDK-master\OpenTok-PHP-SDK-master\sample\HelloWorld\vendor\guzzlehttp\promises\src\Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending()
#7 C:\OpenTok-PHP-SDK-master\OpenTok-PHP-SDK-master\sample\HelloWorld\vendor\guzzlehttp\promises\src\Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList()
#8 C:\OpenTok-PHP-SDK-master\OpenTok-PHP-SDK-master\sample\HelloWorld\vendor\guzzlehttp\promises\src\Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#9 C:\OpenTok-PHP-SDK-master\OpenTok-PHP-SDK-master\sample\HelloWorld\vendor\guzzlehttp\guzzle\src\Client.php(106): GuzzleHttp\Promise\Promise->wait()
#10 C:\OpenTok-PHP-SDK-master\OpenTok-PHP-SDK-master\sample\HelloWorld\vendor\opentok\opentok\src\OpenTok\Util\Client.php(109): GuzzleHttp\Client->send(Object(GuzzleHttp\Psr7\Request), Array)
#11 C:\OpenTok-PHP-SDK-master\OpenTok-PHP-SDK-master\sample\HelloWorld\vendor\opentok\opentok\src\OpenTok\OpenTok.php(225): OpenTok\Util\Client->createSession(Array)
#12 C:\OpenTok-PHP-SDK-master\OpenTok-PHP-SDK-master\sample\HelloWorld\web\index.php(49): OpenTok\OpenTok->createSession()
#13 [internal function]: {closure}('cache/s/e/s/s/i...')
#14 C:\OpenTok-PHP-SDK-master\OpenTok-PHP-SDK-master\sample\HelloWorld\vendor\gregwar\cache\Gregwar\Cache\Cache.php(338): call_user_func(Object(Closure), 'cache/s/e/s/s/i...')
#15 C:\OpenTok-PHP-SDK-master\OpenTok-PHP-SDK-master\sample\HelloWorld\web\index.php(51): Gregwar\Cache\Cache->getOrCreate('sessionId', Array, Object(Closure))
#16 [internal function]: {closure}()
#17 C:\OpenTok-PHP-SDK-master\OpenTok-PHP-SDK-master\sample\HelloWorld\vendor\slim\slim\Slim\Route.php(468): call_user_func_array(Object(Closure), Array)
#18 C:\OpenTok-PHP-SDK-master\OpenTok-PHP-SDK-master\sample\HelloWorld\vendor\slim\slim\Slim\Slim.php(1355): Slim\Route->dispatch()
#19 C:\OpenTok-PHP-SDK-master\OpenTok-PHP-SDK-master\sample\HelloWorld\vendor\slim\slim\Slim\Middleware\Flash.php(85): Slim\Slim->call()
#20 C:\OpenTok-PHP-SDK-master\OpenTok-PHP-SDK-master\sample\HelloWorld\vendor\slim\slim\Slim\Middleware\MethodOverride.php(92): Slim\Middleware\Flash->call()
#21 C:\OpenTok-PHP-SDK-master\OpenTok-PHP-SDK-master\sample\HelloWorld\vendor\slim\slim\Slim\Middleware\PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#22 C:\OpenTok-PHP-SDK-master\OpenTok-PHP-SDK-master\sample\HelloWorld\vendor\slim\slim\Slim\Slim.php(1300): Slim\Middleware\PrettyExceptions->call()
#23 C:\OpenTok-PHP-SDK-master\OpenTok-PHP-SDK-master\sample\HelloWorld\web\index.php(63): Slim\Slim->run()
#24 {main}

**Comment by msach22** [comment]
@geethansip Thanks for reporting. Can you please share the version of the PHP SDK that you're using? 

Are you able to successfully create a session using the REST API from your local machine?

**Comment by geethansip** [comment]
I was able to create a session using REST API. Used postman REST client for this.  same API_Key and API_Secret were used with the PHP SDK. I was trying with the smaple app hello word. 

As per the SDK version, i was using the server SDK avaialble from https://github.com/opentok/OpenTok-PHP-SDK . Not sure what is the version number.

Got the same error with JAVA SDK also. Error log is given below.

C:\Opentok-Java-SDK-master\Opentok-Java-SDK-master>gradlew.bat :sample/HelloWorld:run
:compileJava
:processResources UP-TO-DATE
:classes
:jar
:sample/HelloWorld:compileJava
:sample/HelloWorld:processResources UP-TO-DATE
:sample/HelloWorld:classes
:sample/HelloWorld:run
Exception in thread "main" com.opentok.exception.RequestException: Could not create an OpenTok Session. The server response was invalid. response code: 403
        at com.opentok.util.HttpClient.createSession(HttpClient.java:80)
        at com.opentok.OpenTok.createSession(OpenTok.java:238)
        at com.opentok.OpenTok.createSession(OpenTok.java:291)
        at com.example.HelloWorldServer.main(HelloWorldServer.java:28)
> Building 87% > :sample/HelloWorld:run

**Comment by msach22** [comment]
@geethansip can you share the response details where you're getting the 403?

**Comment by msach22** [comment]
@geethansip Closing this issue due to inactivity, please re-open if the issue still persists.
